companies = [
    {"name": "Acme Inc",
     "salary": 55,
     "employees": 150,
     "reputation": 7.5,
     "distance": 30},
    {"name": "Smith Consulting",
     "salary": 90,
     "employees": 150,
     "reputation": 2.3,
     "distance": 120},
    {"name": "John Engineering",
     "salary": 35,
     "employees": 4,
     "reputation": 9,
     "distance": 10},
    {"name": "myPod",
     "salary": 60,
     "employees": 100,
     "reputation": 6,
     "distance": 40},
    {"name": "DC Electical",
     "salary": 50,
     "employees": 35,
     "reputation": 5,
     "distance": 20},
    {"name": "Masterminds",
     "salary": 88,
     "employees": 350,
     "reputation": 6.1,
     "distance": 49}]

def getCompanyData():
    return companies
